
name: test push tag

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      # - name: Clone Repository
      #   uses: actions/checkout@v2
      - name: Checkout
        uses: actions/checkout@v2
      - name: push tag
        run: |
          echo ${{github.ref}}
      - name: Create Release Notes
        uses: docker://decathlon/release-notes-generator-action:2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILENAME_PREFIX: MyMilestone
      # - uses: mxschmitt/action-tmate@v1
      - uses: mxschmitt/action-tmate@v1
        if: always()

  # release:
  #   if: startsWith(github.ref, 'refs/tags/')
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - name: push tag
  #       run: |
  #         echo ${{github.ref}}
  #     - name: Create Release
  #       id: create_release
  #       uses: actions/create-release@latest
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
  #       with:
  #         tag_name: ${{ github.ref }}
  #         release_name: Release ${{ github.ref }}
  #         body: |
  #           Changes in this Release
  #           - First Change
  #           - Second Change
  #         draft: false
  #         prerelease: false
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Create Release Notes
  #       uses: docker://decathlon/release-notes-generator-action:2.0.1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         FILENAME_PREFIX: MyMilestone
  #     # - uses: mxschmitt/action-tmate@v1
  #     - uses: mxschmitt/action-tmate@v1
  #       if: always()
